FROM centos:latest

WORKDIR /project

RUN yum --assumeyes update

# locale & timezone
RUN localedef -c -i en_GB -f UTF-8 en_GB.UTF-8
ENV LANG "en_GB.UTF-8"
RUN ln -sf /usr/share/zoneinfo/Europe/London /etc/localtime

# basic 'dotfiles' dependencies
RUN yum --assumeyes install \
    bc \
    curl \
    openssl \
    pcre-tools \
    perl \
    rsync \
    sudo \
    wget
# additional 'dotfiles' dependencies
RUN yum --assumeyes install \
    git \
    vim
