FROM debian:latest

WORKDIR /project

RUN apt-get --yes update

# locale & timezone
RUN apt-get --yes --ignore-missing --no-install-recommends install \
        locales \
    && localedef -i en_GB -c -f UTF-8 -A /usr/share/locale/locale.alias en_GB.UTF-8
ENV LANG en_GB.UTF-8
RUN echo "Europe/London" | tee /etc/timezone \
    && dpkg-reconfigure -f noninteractive tzdata

# basic dependencies
RUN apt-get --yes --ignore-missing --no-install-recommends install \
    bc \
    binutils \
    curl \
    openssl \
    pcregrep \
    rsync \
    sudo \
    wget
