FROM ubuntu:latest

WORKDIR /project

ENV DEBIAN_FRONTEND "noninteractive"
RUN apt-get --yes update && apt-get --yes upgrade

# locale & timezone
RUN apt-get --yes --ignore-missing --no-install-recommends install \
        locales \
    && locale-gen en_GB.UTF-8 && update-locale LANG=en_GB.UTF-8 LC_CTYPE=en_GB.UTF-8
ENV LANG "en_GB.UTF-8"
RUN echo "Europe/London" | tee /etc/timezone \
    && dpkg-reconfigure -f noninteractive tzdata

# basic 'dotfiles' dependencies
RUN apt-get --yes --ignore-missing --no-install-recommends install \
    bc \
    binutils \
    curl \
    openssl \
    pcregrep \
    perl \
    rsync \
    sudo \
    wget
# additional 'dotfiles' dependencies
RUN apt-get --yes --ignore-missing --no-install-recommends install \
    git \
    vim
