FROM debian:latest

WORKDIR /project

ENV DEBIAN_FRONTEND "noninteractive"
RUN apt-get --yes update && apt-get --yes upgrade # 2015/12/15

# settings
RUN apt-get --yes --ignore-missing --no-install-recommends install \
        locales \
    && localedef -i en_GB -c -f UTF-8 -A /usr/share/locale/locale.alias en_GB.UTF-8
ENV LANG "en_GB.UTF-8"
RUN echo "Europe/London" | tee /etc/timezone \
    && dpkg-reconfigure -f noninteractive tzdata
RUN apt-get --yes --ignore-missing --no-install-recommends install \
    ca-certificates

# dotfiles tools
RUN apt-get --yes --ignore-missing --no-install-recommends install \
    bash-completion \
    bc \
    binutils \
    curl \
    expect \
    git \
    openssl \
    pcregrep \
    perl \
    python \
    python-pygments \
    rsync \
    sudo \
    unzip \
    wget \
    xz-utils
# common tools
RUN apt-get --yes --ignore-missing --no-install-recommends install \
    ack-grep \
    grc \
    htop \
    lnav \
    mc \
    strace \
    traceroute \
    tree \
    vim \
    zsh
# server tools
RUN apt-get --yes --ignore-missing --no-install-recommends install \
    heirloom-mailx
