FROM stefaniuk/ubuntu

RUN apt-get --yes update \
    \
    # system tools
    && apt-get --yes --ignore-missing --no-install-recommends install \
        apt-file \
        apt-utils \
        debconf-utils \
        software-properties-common

WORKDIR /project
