FROM centos:latest

WORKDIR /project

RUN yum --assumeyes update \
    && yum --assumeyes install epel-release # 2015/12/15

# settings
RUN localedef -c -i en_GB -f UTF-8 en_GB.UTF-8
ENV LANG "en_GB.UTF-8"
RUN ln -sf /usr/share/zoneinfo/Europe/London /etc/localtime
RUN yum --assumeyes install \
    ca-certificates

# dotfiles tools
RUN yum --assumeyes install \
    bash-completion \
    bc \
    curl \
    expect \
    git \
    openssl \
    pcre-tools \
    perl \
    python \
    rsync \
    sudo \
    unzip \
    wget \
    xz
# common tools
RUN yum --assumeyes install \
    ack \
    htop \
    lnav \
    mc \
    strace \
    traceroute \
    tree \
    vim \
    zsh
    # MISSING: grc
# server tools
RUN yum --assumeyes install \
    mailx
