FROM ubuntu:latest

WORKDIR /project

ENV DEBIAN_FRONTEND "noninteractive"
RUN apt-get --yes update && apt-get --yes upgrade

# settings
RUN apt-get --yes --ignore-missing --no-install-recommends install \
        locales \
    && locale-gen en_GB.UTF-8 && update-locale LANG=en_GB.UTF-8 LC_CTYPE=en_GB.UTF-8
ENV LANG "en_GB.UTF-8"
RUN echo "Europe/London" | tee /etc/timezone \
    && dpkg-reconfigure -f noninteractive tzdata
RUN apt-get --yes --ignore-missing --no-install-recommends install \
    ca-certificates

# dependencies
RUN apt-get --yes --ignore-missing --no-install-recommends install \
    bash-completion \
    bc \
    binutils \
    curl \
    expect \
    openssl \
    pcregrep \
    perl \
    rsync \
    sudo \
    wget
# tools
RUN apt-get --yes --ignore-missing --no-install-recommends install \
    ack-grep \
    git \
    git-flow \
    grc \
    vim \
    mc \
    zsh
