#!/bin/bash

################################################################################
# Git                                                                          #
################################################################################

print_title "Configure Git"
git config --global user.name "$USER_NAME"
git config --global user.email "$USER_EMAIL"
git config --global push.default simple

################################################################################

exit 0
