#!/bin/bash

# ### Mac OS X #################################################################

function macosx-install-dependencies-bundle {

    $brew_install \
        bc \
        binutils \
        expect \
        openssl \
        pcre \
        perl \
        python3 \
        rsync \
        unzip \
        wget \
        xz
    sudo easy_install \
        Pygments
}

# ### Ubuntu ###################################################################

function ubuntu-install-dependencies-bundle {

    $apt_get_install \
        bc \
        binutils \
        expect \
        openssl \
        pcregrep \
        perl \
        python \
        python-pygments \
        rsync \
        unzip \
        wget \
        xz-utils
}

function install-dependencies-bundle {

    run_install \
        git \
        vault
}
