#!/bin/bash

# ### Mac OS X #################################################################

function macosx-install-developer-bundle {

    $brew_install \
        git-flow \
        gpg2 \
        gtypist \
        httpie \
        jq \
        make
    run_install \
        iterm \
        remote-desktop
}

function macosx-config-developer-bundle {

    run_config \
        iterm
}

# ### Ubuntu ###################################################################

function ubuntu-install-developer-bundle {

    $apt_get_install \
        git-flow \
        gpgv2 \
        gtypist \
        httpie \
        jq \
        nfs-kernel-server
    run_install \
        remmina \
        ruby
}

# ### common ###################################################################

function install-developer-bundle {

    run_install \
        atom \
        chrome \
        dbeaver \
        docker \
        gitkraken \
        java \
        node \
        smartgit \
        tmux \
        vagrant \
        virtualbox \
        vscode
    npm install -g \
        http-console
}

function config-developer-bundle {

    run_config \
        atom \
        docker \
        git \
        java \
        node \
        tmux \
        vagrant \
        virtualbox \
        vscode
}
