#!/bin/bash

# ### Mac OS X #################################################################

function macosx-install-developer-bundle {

    $brew_install \
        git-flow \
        gpg2 \
        gtypist \
        httpie \
        jq
    run_install \
        iterm \
        remote-desktop
}

function macosx-config-developer-bundle {

    run_config \
        iterm
}

# ### Ubuntu ###################################################################

function ubuntu-install-developer-bundle {

    $apt_get_install \
        git-flow \
        gpgv2 \
        gtypist \
        httpie \
        jq \
        nfs-kernel-server
    run_install \
        remmina \
        ruby
}

# ### common ###################################################################

function install-developer-bundle {

    run_install \
        directory-studio \
        ant \
        atom \
        chrome \
        dbeaver \
        docker \
        emacs \
        go \
        gradle \
        groovy \
        irssi \
        java \
        maven \
        node \
        node-packages \
        packer \
        pgadmin \
        ruby-packages \
        scala \
        smartgit \
        soapui \
        sts \
        subl \
        tmux \
        vagrant \
        virtualbox \
        vscode \
        zsh
    npm install -g \
        http-console
}

function config-developer-bundle {

    run_config \
        ant \
        atom \
        docker \
        git \
        go \
        gradle \
        groovy \
        irssi \
        java \
        maven \
        node \
        node-packages \
        packer \
        ruby \
        scala \
        subl \
        tmux \
        vagrant \
        virtualbox \
        vscode \
        zsh
}
