#!/bin/bash

# ### Mac OS X #################################################################

function macosx-install-stefaniuk-bundle {

    run_install \
        iina
    $brew_install \
        google-drive \
        pandoc
}

# ### Ubuntu ###################################################################

function ubuntu-install-stefaniuk-bundle {

    $apt_get_install \
        aspell \
        hunspell \
        myspell-en-gb \
        pandoc
    run_install \
        compiz \
        enpass \
        vlc
}

# ### common ###################################################################

function install-stefaniuk-bundle {

    run_install \
        dropbox \
        office \
        torrent
}
