#!/bin/bash

# ### Mac OS X #################################################################

function macosx-install-user-bundle {

    $brew_install \
        pandoc
}

# ### Ubuntu ###################################################################

function ubuntu-install-user-bundle {

    $apt_get_install \
        aspell \
        hunspell \
        myspell-en-gb \
        pandoc
    run_install \
        compiz
}

# ### common ###################################################################

function install-user-bundle {

    run_install \
        dropbox \
        enpass
}
