#!/bin/bash

# ### Mac OS X #################################################################

function macosx-install-system-bundle {

    $cask_install \
        bettertouchtool \
        caffeine \
        hammerspoon \
        witch
    run_install \
        karabiner \
        moom
}

# ### Ubuntu ###################################################################

function ubuntu-install-system-bundle {

    $apt_get_install \
        apt-file \
        apt-transport-https \
        apt-utils \
        ca-certificates \
        curl \
        debconf-utils \
        dialog \
        iputils-ping \
        locales \
        netcat \
        software-properties-common \
        strace \
        unzip \
        vim \
        wget
}
