#!/bin/bash

# ### Mac OS X #################################################################

function macosx-install-admin-bundle {

    :
}

function macosx-config-admin-bundle {

    :
}

# ### Ubuntu ###################################################################

function ubuntu-install-admin-bundle {

    :
}

function ubuntu-config-admin-bundle {

    :
}
