#!/bin/bash

# ### Mac OS X #################################################################

function macosx-install-admin-bundle {

    $brew_install \
        ack \
        coreutils \
        diffutils \
        findutils \
        grc \
        htop \
        lnav \
        lsof \
        mc \
        tcptraceroute \
        tree \
        vim
}

# ### Ubuntu ###################################################################

function ubuntu-install-admin-bundle {

    $apt_get_install \
        ack-grep \
        dnsutils \
        grc \
        heirloom-mailx \
        htop \
        iotop \
        iputils-ping \
        lnav \
        lsof \
        mc \
        net-tools \
        netcat \
        strace \
        traceroute \
        tree \
        vim
}

# ### common ###################################################################

function install-admin-bundle {

    run_install \
        bash
}

function config-admin-bundle {

    run_config \
        bash \
        mc \
        ssh \
        vim
}
