#!/bin/bash

# ### common ###################################################################

function install-ant {

    ver=$(www_get http://ant.apache.org/bindownload.cgi | grep 'bin.tar.gz' | egrep -o '[0-9]+\.[0-9]+\.[0-9]+' | sortvr | head -n 1)
    file_download \
        --url "http://mirrors.ukfast.co.uk/sites/ftp.apache.org//ant/binaries/apache-ant-$ver-bin.tar.gz" \
        --file "apache-ant-$ver-bin.tar.gz"
    tar -zxf apache-ant-$ver-bin.tar.gz
    rm -rf $DIR/usr/applications/ant
    mv -v apache-ant-$ver $DIR/usr/applications/ant
    rm apache-ant-$ver-bin.tar.gz
}

function config-ant {

    cat <<EOF > $DIR/etc/profile.d/ant.sh
#!/bin/bash
export PATH=\$PATH:~/usr/applications/ant/bin
EOF
}
