#!/bin/bash

# ### Mac OS X #################################################################

function macosx-install-atom {

    $cask_install atom
}

# ### Ubuntu ###################################################################

function ubuntu-install-atom {

    $apt_add_repository ppa:webupd8team/atom
    $apt_get_update
    $apt_get_install atom
}

# ### common ###################################################################

function config-atom {

    mkdir -p $DIR/.atom
    cp -fv $DIR/lib/resources/atom/config.cson $DIR/.atom
    apm install \
        atom-beautify \
        atom-ide-ui \
        clipboard-plus \
        file-icons \
        git-plus \
        highlight-selected \
        ide-java \
        ide-php \
        ide-python \
        ide-typescript \
        markdown-pdf \
        open-recent \
        pdf-view \
        pigments \
        set-syntax \
        sort-lines
}
