#!/bin/bash

# ### Mac OS X #################################################################

function macosx-install-azure {

    $brew_install azure-cli
}

# ### Ubuntu ###################################################################

function ubuntu-install-azure {

    sudo apt-key adv --keyserver packages.microsoft.com --recv-keys 52E16F86FEE04B979B07E28DB02C46DF417A0893
    sudo sh -c "echo 'deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $(lsb_release -cs) main' > /etc/apt/sources.list.d/azure.list"
    $apt_get_update
    $apt_get_install azure-cli
}
