#!/bin/bash

# ### Mac OS X #################################################################

function macosx-install-bash {

    $brew_install bash
}

function macosx-config-bash {

    _config-bash
    $brew_install bash-completion
    if [ -f $(brew --prefix)/bin/bash ]; then
        sudo -E file_remove_str "\n$(brew --prefix)/bin/bash" /private/etc/shells --multiline
        sudo bash -c "echo $(brew --prefix)/bin/bash >> /private/etc/shells"
        sudo chsh -s $(brew --prefix)/bin/bash $USER
    fi
}

# ### Ubuntu ###################################################################

function ubuntu-config-bash {

    _config-bash
    $apt_get_install bash-completion
}

# ### common ###################################################################

function _config-bash {

    [ -f $DIR/.profile ] && [ ! -f $DIR/.profile.old ] && mv -v $DIR/.profile $DIR/.profile.old
    [ -f $DIR/.bash_profile ] && [ ! -f $DIR/.bash_profile.old ] && mv -v $DIR/.bash_profile $DIR/.bash_profile.old
    cp -fv $DIR/lib/resources/bash/.bash* $DIR
    file_replace_str "USER_NAME=\"unknown\"" "USER_NAME=\"$USER_NAME\"" $DIR/.bash_exports
    file_replace_str "USER_EMAIL=\"unknown\"" "USER_EMAIL=\"$USER_EMAIL\"" $DIR/.bash_exports
    file_replace_str "GITHUB_ACCOUNT=\"unknown\"" "GITHUB_ACCOUNT=\"$GITHUB_ACCOUNT\"" $DIR/.bash_exports
    file_replace_str "GITLAB_ACCOUNT=\"unknown\"" "GITLAB_ACCOUNT=\"$GITLAB_ACCOUNT\"" $DIR/.bash_exports
    file_replace_str "BASH_PROMPT_SHOW_GIT=true" "BASH_PROMPT_SHOW_GIT=$BASH_PROMPT_SHOW_GIT" $DIR/.bash_exports
}
