#!/bin/bash

# ### Mac OS X #################################################################

function macosx-config-bash {

    _config

    $brew_install bash-completion

    sudo file_remove_str "\n$(brew --prefix)/bin/bash" /private/etc/shells --multiline
    sudo bash -c "echo $(brew --prefix)/bin/bash >> /private/etc/shells"
    sudo chsh -s $(brew --prefix)/bin/bash $USER
}

# ### Ubuntu ###################################################################

function ubuntu-config-bash {

    _config

    $apt_get_install bash-completion
}

# ### common ###################################################################

function _config {

    [ -f $DIR/.profile ] && [ ! -f $DIR/.profile.old ] && mv -v $DIR/.profile $DIR/.profile.old
    [ -f $DIR/.bash_profile ] && [ ! -f $DIR/.bash_profile.old ] && mv -v $DIR/.bash_profile $DIR/.bash_profile.old

    cp -fv $DIR/lib/resources/bash/.bash* $DIR

    file_replace_str "USER_NAME=\"unknown\"" "USER_NAME=\"$USER_NAME\"" $DIR/.bash_exports
    file_replace_str "USER_EMAIL=\"unknown\"" "USER_EMAIL=\"$USER_EMAIL\"" $DIR/.bash_exports
    file_replace_str "GITHUB_ACCOUNT=\"unknown\"" "GITHUB_ACCOUNT=\"$GITHUB_ACCOUNT\"" $DIR/.bash_exports
    file_replace_str "GITLAB_ACCOUNT=\"unknown\"" "GITLAB_ACCOUNT=\"$GITLAB_ACCOUNT\"" $DIR/.bash_exports
}
