#!/bin/bash

# ### Mac OS X #################################################################

function macosx-install-boxcryptor {

    $cask_install boxcryptor
}

# ### Ubuntu ###################################################################

function ubuntu-install-boxcryptor {

    rm -rf $app_dir/boxcryptor
    mkdir $app_dir/boxcryptor
    file_download \
        --url "https://www.boxcryptor.com/l/download-linux-portable" \
        --file "Boxcryptor_Portable_Linux64.tar.gz" \
        --download-dir $app_dir/boxcryptor
    (
        cd $app_dir/boxcryptor
        tar -xf Boxcryptor_Portable_Linux64.tar.gz
        rm Boxcryptor_Portable_Linux64.tar.gz
    )
    cp $DIR/lib/resources/boxcryptor/boxcryptor.png $app_dir/boxcryptor
    cat <<EOF > ~/.local/share/applications/boxcryptor.desktop
[Desktop Entry]
Version=1.0
Name=Boxcryptor
Type=Application
Exec=$app_dir/boxcryptor/Boxcryptor_Portable.sh
Icon=$app_dir/boxcryptor/boxcryptor.png
Terminal=false
Categories=Utility;
EOF
}
