#!/bin/bash

# ### Ubuntu ###################################################################

function ubuntu-install-compiz {

    $apt_get_install \
        compiz \
        compiz-plugins-default compiz-plugins \
        compizconfig-settings-manager
}
