#!/bin/bash

# ### Mac OS X #################################################################

function macosx-install-dbeaver {

    $cask_install dbeaver-community
}

# ### Ubuntu ###################################################################

function ubuntu-install-dbeaver {

    $apt_add_repository ppa:serge-rider/dbeaver-ce
    $apt_get_update
    $apt_get_install dbeaver-ce
}
