#!/bin/bash

# ### Mac OS X #################################################################

function macosx-install-dbeaver {

    $cask_install dbeaver-community
}

# ### Ubuntu ###################################################################

function ubuntu-install-dbeaver {

    ver=$(www_get http://dbeaver.jkiss.org/files/ | grep -E '[0-9]+\.[0-9]+\.[0-9]+/' | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+' | sortvr | head -n 1)
    file_download \
        --url "http://dbeaver.jkiss.org/files/$ver/dbeaver-ce_${ver}_amd64.deb" \
        --file "dbeaver-ce_${ver}_amd64.deb"
    sudo dpkg -i dbeaver-ce_${ver}_amd64.deb
    rm dbeaver-ce_${ver}_amd64.deb
}
