#!/bin/bash

#node
#node-packages
# zsh

# ### Mac OS X #################################################################

function macosx-install-developer-bundle {

    :
}

function macosx-config-developer-bundle {

    :
}

# ### Ubuntu ###################################################################

function ubuntu-install-developer-bundle {

    :
}

function ubuntu-config-developer-bundle {

    :
}
