#!/bin/bash

# ### Mac OS X #################################################################

function macosx-install-developer-bundle {

    # TODO: Install missing packages

    $brew_install \
        git-flow \
        gpg2 \
        gtypist \
        irssi \
        zsh

    run_install \
        ant \
        atom \
        docker \
        gradle \
        groovy \
        java \
        maven \
        node \
        node-packages \
        packer \
        scala \
        smartgit \
        subl \
        tmux \
        vagrant \
        virtualbox \
        vscode
}

# ### Ubuntu ###################################################################

function ubuntu-install-developer-bundle {

    $apt_get_install \
        byobu \
        git-flow \
        gpgv2 \
        gtypist \
        irssi \
        nfs-kernel-server \
        zsh

    run_install \
        ant \
        atom \
        docker \
        gradle \
        groovy \
        java \
        maven \
        node \
        node-packages \
        packer \
        scala \
        smartgit \
        subl \
        tmux \
        vagrant \
        virtualbox \
        vscode
}

# ### common ###################################################################

function config-developer-bundle {

    run_config \
        ant \
        atom \
        docker \
        gradle \
        groovy \
        java \
        maven \
        node \
        node-packages \
        packer \
        scala \
        smartgit \
        subl \
        tmux \
        vagrant \
        virtualbox \
        vscode
}
