#!/bin/bash

function ubuntu-install-docker {

    sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
    sudo sh -c "echo 'deb http://apt.dockerproject.org/repo ubuntu-$PSEUDO_NAME main' > /etc/apt/sources.list.d/docker.list"
    $apt_get_update
    $apt_get_install \
        docker-engine
    ver=$(www_get https://github.com/docker/compose | grep '/docker/compose/tree/' | egrep '/[0-9]+\.[0-9]+\.[0-9]+"' | egrep -o '[0-9]+\.[0-9]+\.[0-9]+' | sortvr | head -n 1)
    sudo curl -SL https://github.com/docker/compose/releases/download/$ver/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
    sudo chmod +x /usr/local/bin/docker-compose
}

function config-docker {

    sudo usermod -aG docker $USER

    # completion
    [ -f /etc/bash_completion ] && dir=/etc/bash_completion.d || dir=/usr/local/etc/bash_completion.d
    if [ -d $dir ] && [ ! -f $dir/docker-completion.bash ]; then
        sudo wget \
            https://raw.githubusercontent.com/docker/docker/master/contrib/completion/bash/docker \
            -O $dir/docker-completion.bash
    fi
    if [ -d $dir ] && [ ! -f $dir/docker-compose-completion.bash ]; then
        sudo wget \
            https://raw.githubusercontent.com/docker/compose/master/contrib/completion/bash/docker-compose \
            -O $dir/docker-compose-completion.bash
    fi
}
