#!/bin/bash

# ### Mac OS X #################################################################

function macosx-install-docker {

    $cask_install docker-edge
}

# ### Ubuntu ###################################################################

function ubuntu-install-docker {

    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable edge"
    sudo apt-get --yes update
    sudo apt-get --yes --ignore-missing --no-install-recommends install docker-ce ||:

    ver=$(curl -sSL https://github.com/docker/compose | grep '/docker/compose/tree/' | egrep '/[0-9]+\.[0-9]+\.[0-9]+"' | egrep -o '[0-9]+\.[0-9]+\.[0-9]+' | head -n 1)
    sudo curl -sSL https://github.com/docker/compose/releases/download/$ver/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
    sudo chmod +x /usr/local/bin/docker-compose

    ver=$(curl -sSL https://github.com/docker/machine | grep '/docker/machine/tree/' | egrep '/v[0-9]+\.[0-9]+\.[0-9]+"' | egrep -o '[0-9]+\.[0-9]+\.[0-9]+' | head -n 1)
    sudo curl -sSL https://github.com/docker/machine/releases/download/v$ver/docker-machine-`uname -s`-`uname -m`  -o /usr/local/bin/docker-machine
    sudo chmod +x /usr/local/bin/docker-machine
}

# ### common ###################################################################

function config-docker {

    [ $OS == "linux" ] && sudo usermod -aG docker $USER
    [ -f /etc/bash_completion ] && dir=/etc/bash_completion.d || dir=/usr/local/etc/bash_completion.d
    sudo curl -SL "https://raw.githubusercontent.com/docker/docker-ce/master/components/cli/contrib/completion/bash/docker" -o $dir/docker-ce-completion.bash
    sudo curl -SL "https://raw.githubusercontent.com/docker/compose/master/contrib/completion/bash/docker-compose" -o $dir/docker-compose-completion.bash
    sudo curl -SL "https://raw.githubusercontent.com/docker/machine/master/contrib/completion/bash/docker-machine.bash" -o $dir/docker-compose-machine.bash
}
