#!/bin/bash

# ### Mac OS X #################################################################

function macosx-install-dropbox {

    $cask_install dropbox
}

# ### Ubuntu ###################################################################

function ubuntu-install-dropbox {

    ver=$(www_get https://linux.dropboxstatic.com/packages/ubuntu/ | grep '_amd64.deb' | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+' | sortvr | head -n 1)
    file_download \
        --url "https://linux.dropboxstatic.com/packages/ubuntu/dropbox_${ver}_amd64.deb" \
        --file "dropbox_${ver}_amd64.deb"
    sudo dpkg -i dropbox_${ver}_amd64.deb
    rm dropbox_${ver}_amd64.deb
}
