#!/bin/bash

# ### Mac OS X #################################################################

function macosx-install-dropbox {

    $cask_install \
        dropbox
}

# ### Ubuntu ###################################################################

function ubuntu-install-dropbox {

    ver=$(www_get https://www.dropbox.com/en_GB/install-linux | grep '_amd64.deb' | egrep -o '[0-9]+\.[0-9]+\.[0-9]+' | sortvr | head -n 1)
    file_download \
        --url "https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_${ver}_amd64.deb" \
        --file "dropbox_${ver}_amd64.deb"
    sudo dpkg -i dropbox_${ver}_amd64.deb
    rm dropbox_${ver}_amd64.deb
}
