#!/bin/bash

# ### Mac OS X #################################################################

function macosx-install-enpass {

    $cask_install enpass
}

# ### Ubuntu ###################################################################

function ubuntu-install-enpass {

    :
    # TODO: Install enpass
}
