#!/bin/bash

# ### Mac OS X #################################################################

function macosx-install-git {

    $brew_install \
        git
}

# ### Ubuntu ###################################################################

function ubuntu-install-git {

    $apt_get_install \
        git
}

# ### common ###################################################################

function config-git {

    cp -fv $DIR/lib/resources/git/.git* $DIR

    git config --global user.name "$USER_NAME"
    git config --global user.email "$USER_EMAIL"

    # completion
    local dir
    [ -f /etc/bash_completion ] && dir=/etc/bash_completion.d || dir=/usr/local/etc/bash_completion.d
    sudo wget \
        "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash" \
        -O $dir/git-completion.bash

    # diff-highlight
    sudo rm -f $DIR/usr/bin/diff-highlight
    wget \
        "https://raw.githubusercontent.com/git/git/master/contrib/diff-highlight/diff-highlight" \
        -O $DIR/usr/bin/diff-highlight
    chmod u+x $DIR/usr/bin/diff-highlight
}
