#!/bin/bash

function config-git {

    cp -fv $DIR/lib/resources/git/.git* $DIR

    git config --global user.name "$USER_NAME"
    git config --global user.email "$USER_EMAIL"
    if [ $(comparev $(git --version | grep -oE [0-9]+\.[0-9]+\.[0-9]+) 2.0.0) != "-1" ]; then
        git config --global push.default simple
    else
        git config --global push.default matching
    fi

    # completion
    [ -f /etc/bash_completion ] && dir=/etc/bash_completion.d || dir=/usr/local/etc/bash_completion.d
    if [ -d $dir ] && [ ! -f $dir/git-completion.bash ]; then
        sudo wget \
            https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash \
            -O $dir/git-completion.bash
    fi

    # diff-highlight
    if [ ! -f $DIR/bin/diff-highlight ]; then
        wget \
            https://raw.githubusercontent.com/git/git/master/contrib/diff-highlight/diff-highlight \
            -O $DIR/bin/diff-highlight
        chmod +x $DIR/bin/diff-highlight
    fi
}
