#!/bin/bash

# ### Mac OS X #################################################################

function macosx-install-gitkraken {

    $cask_install gitkraken
}

# ### Ubuntu ###################################################################

function ubuntu-install-gitkraken {

    $apt_get_install \
        libgnome-keyring-dev
    file_download \
        --url "https://release.gitkraken.com/linux/gitkraken-amd64.deb" \
        --file "gitkraken-amd64.deb"
    sudo dpkg -i gitkraken-amd64.deb
    rm gitkraken-amd64.deb
}
