#!/bin/bash

# ### Mac OS X #################################################################

function macosx-install-go {

    $brew_install go
}

# ### Ubuntu ###################################################################

function ubuntu-install-go {

    ver=$(www_get https://golang.org/dl/ | grep 'linux-amd64.tar.gz' | grep -Eo '[0-9]+\.[0-9]+(\.[0-9]+)?' | sortvr | head -n 1)
    file_download \
        --url "https://storage.googleapis.com/golang/go${ver}.linux-amd64.tar.gz" \
        --file "go${ver}.linux-amd64.tar.gz"
    tar -xf go${ver}.linux-amd64.tar.gz
    rm -rf $app_dir/go
    mv go $app_dir/go
    rm go${ver}.linux-amd64.tar.gz
}

function ubuntu-config-go {

    cat <<EOF > $DIR/etc/profile.d/go.sh
#!/bin/bash
export GOROOT=$app_dir/go
export PATH=\$PATH:$app_dir/go/bin
EOF
}
