#!/bin/bash

# ### common ###################################################################

function install-gradle {

    ver=$(www_get https://gradle.org/gradle-download/ | grep 'bin.zip' | grep -Eo '[0-9]+\.[0-9]+(\.[0-9]+)?' | sortvr | head -n 1)
    file_download \
        --url "https://services.gradle.org/distributions/gradle-$ver-bin.zip" \
        --file "gradle-$ver-bin.zip"
    unzip gradle-$ver-bin.zip > /dev/null
    rm -rf $app_dir/gradle
    mv -v gradle-$ver $app_dir/gradle
    rm gradle-$ver-bin.zip
}

function config-gradle {

    cat <<EOF > $DIR/etc/profile.d/gradle.sh
#!/bin/bash
export PATH=\$PATH:$app_dir/gradle/bin
EOF
}
