#!/bin/bash

# ### common ###################################################################

function install-groovy {

    ver=$(www_get http://groovy-lang.org/download.html | grep -Eo 'apache-groovy-binary-[0-9]+\.[0-9]+(\.[0-9]+)?(-[a-z0-9]+)?(-[0-9]+)?\.zip' | grep -Eo '[0-9]+\.[0-9]+(\.[0-9]+)?(-[a-z0-9]+)?(-[0-9]+)?' | sortvr | head -n 1)
    file_download \
        --url "https://dl.bintray.com/groovy/maven/apache-groovy-binary-$ver.zip" \
        --file "apache-groovy-binary-$ver.zip"
    unzip apache-groovy-binary-$ver.zip > /dev/null
    rm -rf $app_dir/groovy
    mv -v groovy-$ver $app_dir/groovy
    rm apache-groovy-binary-$ver.zip
}

function config-groovy {

    cat <<EOF > $DIR/etc/profile.d/groovy.sh
#!/bin/bash
export PATH=\$PATH:$app_dir/groovy/bin
EOF
}
