#!/bin/bash

# ### Mac OS X #################################################################

function macosx-install-irssi {

    $brew_install irssi
}

# ### Ubuntu ###################################################################

function ubuntu-install-irssi {

    $apt_get_install irssi
}

# ### common ###################################################################

function config-irssi {

    mkdir -p $DIR/.irssi
    cp -fv $DIR/lib/resources/irssi/config $DIR/.irssi
    file_replace_str "real_name = \"\"" "real_name = \"$USER_NAME\"" $DIR/.irssi/config
}
