#!/bin/bash

# ### Mac OS X #################################################################

function macosx-install-node {

    $cask_install \
        java
}

# ### Ubuntu ###################################################################

function ubuntu-install-java {

    $apt_add_repository ppa:webupd8team/java
    $apt_get_update
    echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections
    echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections
    $apt_get_install \
        oracle-java8-installer \
        oracle-java8-set-default
}
