#!/bin/bash

# ### Mac OS X #################################################################

function macosx-install-java {

    $cask_install \
        java8 \
        java
    run_install \
        jenv
}

function macosx-config-java {

    run_config \
        jenv
}

# ### Ubuntu ###################################################################

function ubuntu-install-java {

    $apt_get_install \
        openjdk-8-jdk \
        openjdk-8-jre
}
