#!/bin/bash

# ### Mac OS X #################################################################

function macosx-install-karabiner {

    $cask_install karabiner
}

function config-karabiner {

    cp -fv $DIR/lib/resources/karabiner/private.xml $DIR/Library/Application\ Support/Karabiner
    /usr/local/bin/karabiner set repeat.initial_wait 250
    /usr/local/bin/karabiner set repeat.wait 33
    /usr/local/bin/karabiner enable custom.remap_caps_lock
    /usr/local/bin/karabiner enable custom.correct_shift_keys
    /usr/local/bin/karabiner reloadxml
}
