#!/bin/bash

# ### Ubuntu ###################################################################

function ubuntu-config-locale {

    sudo locale-gen en_GB.UTF-8
    $apt_get_install \
        aspell \
        hunspell \
        myspell-en-gb
}
