#!/bin/bash

# ### common ###################################################################

function install-maven {

    ver=$(www_get https://maven.apache.org/download.cgi | grep 'bin.tar.gz' | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+' | sortvr | head -n 1)
    file_download \
        --url "http://mirrors.ukfast.co.uk/sites/ftp.apache.org/maven/maven-3/$ver/binaries/apache-maven-$ver-bin.tar.gz" \
        --file "apache-maven-$ver-bin.tar.gz"
    tar -xf apache-maven-$ver-bin.tar.gz
    rm -rf $DIR/usr/applications/maven
    mv -v apache-maven-$ver $DIR/usr/applications/maven
    rm apache-maven-$ver-bin.tar.gz
}

function config-maven {

    mkdir -p $DIR/.m2
    cp -fv $DIR/lib/resources/maven/settings*.xml $DIR/.m2
    cat <<EOF > $DIR/etc/profile.d/maven.sh
#!/bin/bash
export PATH=\$PATH:~/usr/applications/maven/bin
EOF
}
