#!/bin/bash

# ### Mac OS X #################################################################

function macosx-install-moom {

    id=$(mas search Moom | awk '{ print $1 }')
    $mas_install $id
    # SEE: https://www.spectacleapp.com/
}

function macosx-config-moom {

    defaults import com.manytricks.Moom $DIR/lib/resources/moom/com.manytricks.Moom.plist
}
