#!/bin/bash

# ### Mac OS X #################################################################

function macosx-install-node {

    run_install \
        nvm
    run_config \
        nvm
}

# ### Ubuntu ###################################################################

function ubuntu-install-node {

    curl -SL https://deb.nodesource.com/setup_10.x | sudo -E bash -
    $apt_get_install nodejs
    sudo npm update -g
}

# ### common ###################################################################

function config-node {

    [ -f /etc/bash_completion ] && dir=/etc/bash_completion.d || dir=/usr/local/etc/bash_completion.d
    sudo /bin/bash -c "npm completion > $dir/node-completion.bash"
}
