#!/bin/bash

function install-node-packages {

    sudo npm install -g \
        angular2-cli \
        bower \
        grunt-cli \
        gulp-cli \
        json \
        typescript \
        typings \
        yo
}
