#!/bin/bash

# ### common ###################################################################

function install-node-packages {

    npm install -g \
        @angular/cli \
        create-react-app \
        json \
        typescript \
        yarn \
        yo
}
