#!/bin/bash

# ### Mac OS X #################################################################

function macosx-install-node {

    $brew_install \
        node
    sudo npm update -g
}

# ### Ubuntu ###################################################################

function ubuntu-install-node {

    curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
    $apt_get_install \
        nodejs
    sudo npm update -g
}

# ### common ###################################################################

function config-node {

    local dir
    [ -f /etc/bash_completion ] && dir=/etc/bash_completion.d || dir=/usr/local/etc/bash_completion.d
    sudo /bin/bash -c "npm completion > $dir/node-completion.bash"
}
