#!/bin/bash

# ### Mac OS X #################################################################

function macosx-install-nvm {

    $brew_install \
        nvm
}

function macosx-config-nvm {

    echo 'export NVM_DIR=~/.nvm' > $DIR/etc/profile.d/nvm
    echo 'source $(brew --prefix nvm)/nvm.sh' >> $DIR/etc/profile.d/nvm
    source $DIR/etc/profile.d/nvm
    nvm install --latest-npm

    [ -f /etc/bash_completion ] && dir=/etc/bash_completion.d || dir=/usr/local/etc/bash_completion.d
    sudo /bin/bash -c "npm completion > $dir/node-completion.bash"
}
