#!/bin/bash

# ### Mac OS X #################################################################

function macosx-install-office {

    $cask_install microsoft-office
}

# ### Ubuntu ###################################################################

function ubuntu-install-office {

    $apt_add_repository ppa:libreoffice/ppa
    $apt_get_update
    $apt_get_install openoffice
}
