#!/bin/bash

# ### Mac OS X #################################################################

function macosx-install-packer {

    $brew_install packer
}

# ### Ubuntu ###################################################################

function ubuntu-install-packer {

    ver=$(www_get https://www.packer.io/downloads.html | grep '_linux_amd64.zip' | grep -E '/[0-9]+\.[0-9]+\.[0-9]+' | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+' | sortvr | head -n 1)
    file_download \
        --url "https://releases.hashicorp.com/packer/$ver/packer_${ver}_linux_amd64.zip" \
        --file "packer_${ver}_linux_amd64.zip"
    sudo unzip -o packer_${ver}_linux_amd64.zip -d /usr/local/bin
    rm packer_${ver}_linux_amd64.zip
}

# ### common ###################################################################

function config-packer {

    [ -f /etc/bash_completion ] && dir=/etc/bash_completion.d || dir=/usr/local/etc/bash_completion.d
    sudo curl -SL "https://raw.githubusercontent.com/Bash-it/bash-it/master/completion/available/packer.completion.bash" -o $dir/packer-completion.bash
}
