#!/bin/bash

function ubuntu-install-packer {

    ver=$(www_get https://www.packer.io/downloads.html | grep '_linux_amd64.zip' | egrep '/[0-9]+\.[0-9]+\.[0-9]+' | egrep -o '[0-9]+\.[0-9]+\.[0-9]+' | sortvr | head -n 1)
    file_download \
        --url "https://releases.hashicorp.com/packer/$ver/packer_${ver}_linux_amd64.zip" \
        --file "packer_${ver}_linux_amd64.zip"
    sudo unzip -o packer_${ver}_linux_amd64.zip -d /usr/local/bin
    rm packer_${ver}_linux_amd64.zip
}
