#!/bin/bash

# ### Mac OS X #################################################################

function macosx-install-phpstorm {

    $cask_install phpstorm
}

# ### Ubuntu ###################################################################

function ubuntu-install-phpstorm {

    :
}
