#!/bin/bash

# ### common ###################################################################

function install-ruby-packages {

    sudo gem install \
        bundler \
        jekyll \
        json \
        rake
}
