#!/bin/bash

# ### common ###################################################################

function install-scala {

    ver=$(www_get http://www.scala-lang.org/download/ | grep '.tgz' | grep -Eo '[0-9]+\.[0-9]+(\.[0-9]+)?' | sortvr | head -n 1)
    file_download \
        --url "http://downloads.lightbend.com/scala/$ver/scala-$ver.tgz" \
        --file "scala-$ver.tgz"
    tar -xf scala-$ver.tgz
    rm -rf $app_dir/scala
    mv -v scala-$ver $app_dir/scala
    rm scala-$ver.tgz
}

function config-scala {

    cat <<EOF > $DIR/etc/profile.d/scala.sh
#!/bin/bash
export PATH=\$PATH:$app_dir/scala/bin
EOF
}
