#!/bin/bash

# ### Mac OS X #################################################################

function macosx-install-smartgit {

    $cask_install smartgit
}

# ### Ubuntu ###################################################################

function ubuntu-install-smartgit {

    ver=$(www_get https://www.syntevo.com/smartgit/download | grep '.tar.gz' | grep -Eo '[0-9]+_[0-9]+_[0-9]+' | sortvr | head -n 1)
    file_download \
        --url "https://www.syntevo.com/downloads/smartgit/smartgit-linux-$ver.tar.gz" \
        --file "smartgit-linux-$ver.tar.gz"
    tar -xf smartgit-linux-$ver.tar.gz
    rm -rf $app_dir/smartgit
    mv -fv smartgit $app_dir/smartgit
    rm smartgit-linux-$ver.tar.gz
    cat <<EOF > ~/.local/share/applications/smartgit.desktop
[Desktop Entry]
Version=1.0
Name=SmartGit
Type=Application
Exec=$app_dir/smartgit/bin/smartgit.sh
Icon=$app_dir/smartgit/bin/smartgit-64.png
Terminal=false
Categories=Utility;
EOF
}
