#!/bin/bash

# ### common ###################################################################

function config-ssh {

    mkdir -p $DIR/.ssh
    chmod 700 $DIR/.ssh

    cp -fv $DIR/lib/resources/ssh/config $DIR/.ssh
    if [ -n "$GITHUB_ACCOUNT" ]; then
        file_replace_str "github-user" "github-$GITHUB_ACCOUNT" $DIR/.ssh/config
    fi
    if [ -n "$GITLAB_ACCOUNT" ]; then
        file_replace_str "gitlab-user" "github-$GITLAB_ACCOUNT" $DIR/.ssh/config
    fi
    if [ -n "$BITBUCKET_ACCOUNT" ]; then
        file_replace_str "bitbucket-user" "bitbucket-$BITBUCKET_ACCOUNT" $DIR/.ssh/config
    fi
}
