#!/bin/bash

# ### Mac OS X #################################################################

function macosx-install-system-bundle {

    $brew_install \
        mas
    $cask_install \
        bettertouchtool \
        caffeine \
        hammerspoon \
        witch
    run_install \
        karabiner \
        moom
}

# ### Ubuntu ###################################################################

function ubuntu-install-system-bundle {

    $apt_get_install \
        apt-file \
        apt-transport-https \
        apt-utils \
        ca-certificates \
        debconf-utils \
        dialog \
        locales \
        software-properties-common
}

# ### common ###################################################################

function config-dependencies-bundle {

    run_config \
        locale \
        timezone
}
