#!/bin/bash

# ### Mac OS X #################################################################

function macosx-install-system-bundle {

    # TODO: configure below packages

    $cask_install \
        seil \
        karabiner \
        bettertouchtool \
        witch \
        moom
}

# ### Ubuntu ###################################################################

function ubuntu-install-system-bundle {

    $apt_get_install \
        apt-file \
        apt-transport-https \
        apt-utils \
        ca-certificates \
        debconf-utils \
        dialog \
        locales \
        software-properties-common
}
