#!/bin/bash

# ### Mac OS X #################################################################

function macosx-install-terraform {

    $brew_install terraform
}

# ### Ubuntu ###################################################################

function ubuntu-install-terraform {

    :
}
