#!/bin/bash

# ### Mac OS X #################################################################

function macosx-install-user-bundle {

    $brew_install \
        pandoc
}

# ### Ubuntu ###################################################################

function ubuntu-install-user-bundle {

    $apt_get_install \
        pandoc
}

# ### common ###################################################################

function install-user-bundle {

    run_install \
        boxcryptor \
        dropbox \
        megasync \
        xmarks
}
