#!/bin/bash

# ### Mac OS X #################################################################

function macosx-install-user-bundle {

    :
}

function macosx-config-user-bundle {

    :
}

# ### Ubuntu ###################################################################

function ubuntu-install-user-bundle {

    :
}

function ubuntu-config-user-bundle {

    :
}
