#!/bin/bash

# ### Mac OS X #################################################################

function macosx-install-vagrant {

    $cask_install \
        vagrant
}

# ### Ubuntu ###################################################################

function ubuntu-install-vagrant {

    ver=$(www_get https://www.vagrantup.com/downloads.html | grep 'x86_64.deb' | egrep '/[0-9]+\.[0-9]+\.[0-9]+' | egrep -o '[0-9]+\.[0-9]+\.[0-9]+' | sortvr | head -n 1)
    file_download \
        --url "https://releases.hashicorp.com/vagrant/$ver/vagrant_${ver}_x86_64.deb" \
        --file "vagrant_${ver}_x86_64.deb"
    sudo dpkg -i vagrant_${ver}_x86_64.deb
    rm vagrant_${ver}_x86_64.deb
}

# ### common ###################################################################

function config-vagrant {

    # completion
    local dir
    [ -f /etc/bash_completion ] && dir=/etc/bash_completion.d || dir=/usr/local/etc/bash_completion.d
    sudo wget \
        "https://raw.githubusercontent.com/Bash-it/bash-it/master/completion/available/vagrant.completion.bash" \
        -O $dir/vagrant-completion.bash
}
