#!/bin/bash

function ubuntu-install-vagrant {

    ver=$(www_get https://www.vagrantup.com/downloads.html | grep 'x86_64.deb' | egrep '/[0-9]+\.[0-9]+\.[0-9]+' | egrep -o '[0-9]+\.[0-9]+\.[0-9]+' | sortvr | head -n 1)
    file_download \
        --url "https://releases.hashicorp.com/vagrant/$ver/vagrant_${ver}_x86_64.deb" \
        --file "vagrant_${ver}_x86_64.deb"
    sudo dpkg -i vagrant_${ver}_x86_64.deb
    rm vagrant_${ver}_x86_64.deb
}

function config-vagrant {

    # completion
    [ -f /etc/bash_completion ] && dir=/etc/bash_completion.d || dir=/usr/local/etc/bash_completion.d
    if [ -d $dir ] && [ ! -f $dir/vagrant-completion.bash ]; then
        sudo wget \
            https://raw.github.com/kura/vagrant-bash-completion/master/etc/bash_completion.d/vagrant \
            -O $dir/vagrant-completion.bash
    fi
}
