#!/bin/bash

# ### Mac OS X #################################################################

function macosx-install-virtualbox {

    $cask_install virtualbox virtualbox-extension-pack
}

# ### Ubuntu ###################################################################

function ubuntu-install-virtualbox {

    wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -
    wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -
    sudo sh -c "echo 'deb http://download.virtualbox.org/virtualbox/debian $PSEUDO_NAME contrib' > /etc/apt/sources.list.d/virtualbox.list"
    $apt_get_update
    $apt_get_install virtualbox-5.2

    ver=$(curl -sSL http://download.virtualbox.org/virtualbox/ | grep 'href' | egrep -o '[0-9]+\.[0-9]+\.[0-9]+' | sort -r | head -n 1)
    file_download \
        --url "http://download.virtualbox.org/virtualbox/$ver/Oracle_VM_VirtualBox_Extension_Pack-$ver.vbox-extpack" \
        --file "Oracle_VM_VirtualBox_Extension_Pack-$ver.vbox-extpack"
    echo "y" | sudo VBoxManage extpack install Oracle_VM_VirtualBox_Extension_Pack-$ver.vbox-extpack
    rm Oracle_VM_VirtualBox_Extension_Pack-$ver.vbox-extpack
}

# ### common ###################################################################

function config-virtualbox {

    [ -f /etc/bash_completion ] && dir=/etc/bash_completion.d || dir=/usr/local/etc/bash_completion.d
    sudo curl -SL "https://raw.githubusercontent.com/Bash-it/bash-it/master/completion/available/virtualbox.completion.bash" -o $dir/virtualbox-completion.bash
}
