#!/bin/bash

# ### Mac OS X #################################################################

function macosx-install-vlc {

    $cask_install vlc
}

# ### Ubuntu ###################################################################

function ubuntu-install-vlc {

    :
}
