#!/bin/bash

# ### Mac OS X #################################################################

function macosx-install-vscode {

    $cask_install visual-studio-code
}

function macosx-config-vscode {

    dir=$DIR/Library/Application\ Support
}

# ### Ubuntu ###################################################################

function ubuntu-install-vscode {

    ver=$(www_get https://code.visualstudio.com/updates | grep -Eo 'v[0-9]+_[0-9]+' | sortvr | head -n 1)
    # TODO: Download Visual Studio Code
    # SEE: https://code.visualstudio.com/docs/setup/linux
    #file_download \
    #    --url "https://vscode-update.azurewebsites.net/$ver/linux-deb-x64/stable" \
    #    --file "vscode-$ver.deb"
    #sudo dpkg -i vscode-$ver.deb
    #rm vscode-$ver.deb
}

function ubuntu-config-vscode {

    dir=$DIR/.config
}

# ### common ###################################################################

function config-vscode {

    mkdir -p "$dir/Code/User"
    cp -fv $DIR/lib/resources/vscode/settings.json "$dir/Code/User"

    code --force --install-extension dbaeumer.vscode-eslint
    code --force --install-extension eamodio.gitlens
    code --force --install-extension editorconfig.editorconfig
    code --force --install-extension ms-python.python
    code --force --install-extension ms-vscode.cpptools
    code --force --install-extension ms-vscode.csharp
    code --force --install-extension ms-vscode.go
    code --force --install-extension msjsdiag.debugger-for-chrome
    code --force --install-extension pivotal.vscode-spring-boot
    code --force --install-extension redhat.java
    code --force --install-extension vscjava.vscode-spring-boot-dashboard
    code --force --install-extension vscjava.vscode-spring-initializr
    code --force --install-extension vsmobile.vscode-react-native
}
