#!/bin/bash

# ### Mac OS X #################################################################

function macosx-install-vscode {

    $cask_install visual-studio-code
}

function macosx-config-vscode {

    dir=$DIR/Library/Application\ Support
}

# ### Ubuntu ###################################################################

function ubuntu-install-vscode {

    ver=$(www_get https://code.visualstudio.com/updates | grep -Eo 'v[0-9]+_[0-9]+' | sortvr | head -n 1)
    # TODO: Download Visual Studio Code
    # SEE: https://code.visualstudio.com/docs/setup/linux
    #file_download \
    #    --url "https://vscode-update.azurewebsites.net/$ver/linux-deb-x64/stable" \
    #    --file "vscode-$ver.deb"
    #sudo dpkg -i vscode-$ver.deb
    #rm vscode-$ver.deb
}

function ubuntu-config-vscode {

    dir=$DIR/.config
}

# ### common ###################################################################

function config-vscode {

    mkdir -p "$dir/Code/User"
    cp -fv $DIR/lib/resources/vscode/settings.json "$dir/Code/User"

    code --force --install-extension coenraads.bracket-pair-colorizer
    code --force --install-extension dbaeumer.vscode-eslint
    code --force --install-extension eamodio.gitlens
    code --force --install-extension editorconfig.editorconfig
    code --force --install-extension felixfbecker.php-debug
    code --force --install-extension felixfbecker.php-intellisense
    code --force --install-extension gabrielbb.vscode-lombok
    code --force --install-extension ginfuru.ginfuru-better-solarized-dark-theme
    code --force --install-extension jmrog.vscode-nuget-package-manager
    code --force --install-extension johnpapa.vscode-peacock
    code --force --install-extension marcostazi.vs-code-vagrantfile
    code --force --install-extension mauve.terraform
    code --force --install-extension mhutchie.git-graph
    code --force --install-extension ms-python.anaconda-extension-pack
    code --force --install-extension ms-python.python
    code --force --install-extension ms-vscode-remote.remote-containers
    code --force --install-extension ms-vscode.cpptools
    code --force --install-extension ms-vscode.csharp
    code --force --install-extension ms-vscode.go
    code --force --install-extension ms-vsliveshare.vsliveshare-pack
    code --force --install-extension msjsdiag.debugger-for-chrome
    code --force --install-extension msjsdiag.vscode-react-native
    code --force --install-extension oderwat.indent-rainbow
    code --force --install-extension pivotal.vscode-spring-boot
    code --force --install-extension redhat.java
    code --force --install-extension ritwickdey.liveserver
    code --force --install-extension streetsidesoftware.code-spell-checker
    code --force --install-extension vscjava.vscode-spring-boot-dashboard
    code --force --install-extension vscjava.vscode-spring-initializr
    code --force --install-extension vscode-icons-team.vscode-icons
}
