#!/bin/bash

# ### Mac OS X #################################################################

function macosx-install-zsh {

    $brew_install zsh
}

function macosx-config-zsh {

    if [ -f $(brew --prefix)/bin/zsh ]; then
        sudo -E file_remove_str "\n$(brew --prefix)/bin/zsh" /private/etc/shells --multiline
        sudo bash -c "echo $(brew --prefix)/bin/zsh >> /private/etc/shells"
    fi
}

# ### Ubuntu ###################################################################

function ubuntu-install-zsh {

    $apt_get_install zsh
}

# ### common ###################################################################

function config-zsh {

    if [ ! -f $DIR/.oh-my-zsh/oh-my-zsh.sh ]; then
        rm -rf $DIR/{.oh-my-zsh,.zcompdump-*,.zlogin}
        git clone https://github.com/robbyrussell/oh-my-zsh.git $DIR/.oh-my-zsh
    elif [ -d $DIR/.oh-my-zsh/.git ]; then
        (cd $DIR/.oh-my-zsh; git pull)
    fi
    cp -fv $DIR/lib/resources/zsh/.zsh* $DIR
}
