#!/bin/bash

if should_config "ant"; then

    print_h2 "Ant"

    cat <<EOF > $DIR/lib/profile.d/ant.sh
#!/bin/bash
export PATH=\$PATH:~/usr/applications/ant/bin
EOF
    chmod +x $DIR/lib/profile.d/ant.sh

fi
