#!/bin/bash

if should_config "irssi"; then

    print_h2 "Irssi"

    mkdir -p $DIR/.irssi
    cp -f $DIR/lib/irssi/config $DIR/.irssi
    file_replace_str "real_name = \"\"" "real_name = \"$USER_NAME\"" $DIR/.irssi/config

fi

if should_config "go"; then

    print_h2 "Go"

    cat <<EOF > $DIR/lib/profile.d/go.sh
#!/bin/bash
export GOROOT=~/usr/applications/go
export PATH=\$PATH:~/usr/applications/go/bin
EOF
    chmod +x $DIR/lib/profile.d/go.sh

fi

if should_config "groovy"; then

    print_h2 "Groovy"

    cat <<EOF > $DIR/lib/profile.d/groovy.sh
#!/bin/bash
export PATH=\$PATH:~/usr/applications/groovy/bin
EOF
    chmod +x $DIR/lib/profile.d/groovy.sh

fi

if should_config "scala"; then

    print_h2 "Scala"

    cat <<EOF > $DIR/lib/profile.d/scala.sh
#!/bin/bash
export PATH=\$PATH:~/usr/applications/scala/bin
EOF
    chmod +x $DIR/lib/profile.d/scala.sh

fi

if should_config "gradle"; then

    print_h2 "Gradle"

    cat <<EOF > $DIR/lib/profile.d/gradle.sh
#!/bin/bash
export PATH=\$PATH:~/usr/applications/gradle/bin
EOF
    chmod +x $DIR/lib/profile.d/gradle.sh

fi

if should_config "maven"; then

    print_h2 "Maven"

    mkdir -p $DIR/.m2
    cp -f $DIR/lib/maven/settings*.xml $DIR/.m2

    cat <<EOF > $DIR/lib/profile.d/maven.sh
#!/bin/bash
export PATH=\$PATH:~/usr/applications/maven/bin
EOF
    chmod +x $DIR/lib/profile.d/maven.sh

fi

if should_config "ant"; then

    print_h2 "Ant"

    cat <<EOF > $DIR/lib/profile.d/ant.sh
#!/bin/bash
export PATH=\$PATH:~/usr/applications/ant/bin
EOF
    chmod +x $DIR/lib/profile.d/ant.sh

fi
