#!/bin/bash

if should_config "maven"; then

    print_h2 "Maven"

    mkdir -p $DIR/.m2
    cp -f $DIR/lib/maven/settings*.xml $DIR/.m2

    cat <<EOF > $DIR/lib/profile.d/maven.sh
#!/bin/bash
export PATH=\$PATH:~/usr/applications/maven/bin
EOF
    chmod +x $DIR/lib/profile.d/maven.sh

fi

if should_config "ant"; then

    print_h2 "Ant"

    cat <<EOF > $DIR/lib/profile.d/ant.sh
#!/bin/bash
export PATH=\$PATH:~/usr/applications/ant/bin
EOF
    chmod +x $DIR/lib/profile.d/ant.sh

fi
