#!/bin/bash

# ### Ubuntu ###################################################################

if [ $DIST = "ubuntu" ]; then

    if [ -f /etc/sudoers ] && sudo cat /etc/sudoers | grep "env_reset" > /dev/null || sudo cat /etc/sudoers | grep "secure_path" > /dev/null; then
        print_h2 "Sudo"
        sudo $DIR/bin/file_remove_str "Defaults[[:space:]]+env_reset" /etc/sudoers
        sudo $DIR/bin/file_remove_str "Defaults[[:space:]]+secure_path=\".*\"" /etc/sudoers
    fi

fi
