#!/bin/bash

########################################################################################################################
### REFACTOR ###########################################################################################################
########################################################################################################################

$cask_install dropbox
$cask_install megasync
$cask_install google-drive
$cask_install boxcryptor

#     $cask_install asepsis --appdir=/Applications
#     $cask_install caffeine --appdir=/Applications
#     $cask_install menumeters --appdir=/Applications
#     $cask_install android-file-transfer --appdir=/Applications

#     $cask_install iterm2-beta
#     $cask_install github-desktop
#     $cask_install smartsynchronize
#     $cask_install filezilla
#     $cask_install sts
#     $cask_install phpstorm
#     $cask_install android-studio
#     $brew_install android-sdk
#     $brew_install android-ndk
#     $cask_install pgadmin3
#     $cask_install rdm
#     $cask_install apache-directory-studio
#     $cask_install xquartz wireshark
#     $cask_install gimp

#     $cask_install xtrafinder
#     $cask_install firefox --appdir=/Applications
#     $cask_install firefoxdeveloperedition --appdir=/Applications
#     $cask_install flash
#     $cask_install adobe-reader
#     $cask_install xee22
#     $cask_install vox
#     $cask_install vlc
