#!/bin/bash

if should_config "dependencies"; then
    run_config \
        git
fi

if should_config "system-bundle"; then
    :
fi

if should_config "admin-bundle"; then
    run_config \
        bash
fi

if should_config "developer-bundle"; then
    run_config \
        node
fi

if should_config "user-bundle"; then
    :
fi

config_app \
    bash \
    git \
    node

exit 0 # TODO: Remove this line once refactored

########################################################################################################################
### REFACTOR ###########################################################################################################
########################################################################################################################

if should_config "subl"; then

    print_h2 "Sublime Text"

    cp -f $DIR/lib/subl/ubuntu/* $DIR/.config/sublime-text-3/Packages/User

fi
