#!/bin/bash

########################################################################################################################
### REFACTOR ###########################################################################################################
########################################################################################################################

if should_install "system-bundle"; then
    print_h2 "System Bundle"
    $apt_get_install \
        apt-file \
        apt-transport-https \
        apt-utils \
        ca-certificates \
        debconf-utils \
        dialog \
        locales \
        software-properties-common
fi

if should_install "admin-bundle"; then
    print_h2 "Admin Bundle"
    $apt_get_install \
        ack-grep \
        grc \
        heirloom-mailx \
        htop \
        iputils-ping \
        lnav \
        lsof \
        lynx \
        mc \
        net-tools \
        netcat \
        strace \
        traceroute \
        tree \
        vim
fi

if should_install "developer-bundle"; then
    print_h2 "Developer Bundle"
    $apt_get_install \
        byobu \
        git-flow \
        gpgv2 \
        gtypist \
        irssi \
        nfs-kernel-server \
        tmux \
        zsh
fi
