#!/bin/bash

if should_config "dependencies"; then
    run_config \
        git
fi

if should_config "system-bundle"; then
    :
fi

if should_config "admin-bundle"; then
    run_config \
        bash
fi

if should_config "developer-bundle"; then
    run_config \
        node
fi

if should_config "user-bundle"; then
    :
fi

config_app \
    bash \
    git \
    node
