#!/bin/bash

# ### Mac OS X #################################################################

if [ $DIST = "macosx" ]; then

    print_h2 "Lists of packages"
    $brew_update
    print_h2 "Packages"
    $brew_upgrade

fi

# ### Ubuntu ###################################################################

if [ $DIST = "ubuntu" ]; then

    print_h2 "Lists of packages"
    $apt_get_update
    print_h2 "Packages"
    $apt_get_upgrade

fi
