#!/bin/bash

alias d="docker"
alias dim="docker images"
alias dps="docker ps --all"
alias dst="docker start"
alias dto="docker top"
alias dlo="docker logs --follow"
alias dex="docker exec --interactive --tty"
alias dat="docker attach"
alias dip="docker inspect --format '{{ .NetworkSettings.IPAddress }}'"
alias drc='docker rm --volumes --force $(docker ps --all --quiet) 2> /dev/null'
alias drv='docker volume rm $(docker volume ls --quiet --filter dangling=true) 2> /dev/null'
alias dri='docker rmi --force $(docker images | grep "<none>" | awk "{print $3}") 2> /dev/null'
alias dri-own='docker rmi --force $(docker images | grep "$GITHUB_ACCOUNT" | awk "{print $3}") 2> /dev/null'
