FROM ubuntu:16.04

ARG APT_PROXY
ARG APT_PROXY_SSL

RUN set -ex \
    \
    && if [ -n "$APT_PROXY" ]; then echo "Acquire::http { Proxy \"http://${APT_PROXY}\"; };" > /etc/apt/apt.conf.d/00proxy; fi \
    && if [ -n "$APT_PROXY_SSL" ]; then echo "Acquire::https { Proxy \"https://${APT_PROXY_SSL}\"; };" > /etc/apt/apt.conf.d/00proxy; fi \
    && echo "APT::Install-Recommends 0;\nAPT::Install-Suggests 0;" >> /etc/apt/apt.conf.d/01norecommends \
    && apt-get --yes update \
    && apt-get --yes upgrade \
    && apt-get --yes install \
        curl \
        gosu \
        rsync \
    \
    && rm -f /etc/apt/apt.conf.d/00proxy

WORKDIR /project
