VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    config.vm.provider :virtualbox do |vb|
        vb.name = "dotfiles"
        vb.cpus = 2
        vb.memory = 1024
        vb.customize ["modifyvm", :id, "--ioapic", "on"]
        vb.customize ["modifyvm", :id, "--cpuexecutioncap", "66"]
    end

    config.vm.box = "ubuntu/trusty64"
    config.vm.hostname = "dotfiles"
    config.vm.synced_folder "..", "/project"
    config.vm.provision "shell", path: "provision.sh"

end
