PROJECT := project

help:
	@echo
	@echo "Usage:"
	@echo
	@echo "    make export-project|validate-project-archive"
	@echo

export-project:
	@echo "Exporting project..."
	@git archive --format=tar.gz --prefix=$(PROJECT)/ HEAD > dist/$(PROJECT).tar.gz
	@cd dist; sha256sum $(PROJECT).tar.gz > $(PROJECT).tar.gz.sha256
validate-project-archive:
	@echo "Validating project archive..."
	@cd dist; sha256sum -c $(PROJECT).tar.gz.sha256

.PHONY:
.SILENT:
